### ISSUE TITLE
WebGL 2.0 not working on iPhone X iOS 12.1.4

### ISSUE THREAD

**Issue by technicgb** [magcius/noclip.website#15] opened 2019-02-26 12:57 UTC
inside the iPhone settings>safari>advanced> Experimental>webGL2.0/webgpu

**Comment by TimvanScherpenzeel** [comment] 2019-02-26 13:58
Please see: https://github.com/magcius/noclip.website/issues/10#issuecomment-467447462

**Comment by magcius** [comment] 2019-02-26 15:30
Closing as duplicate of #10.

**Closed** 2019-02-26 17:58 UTC
Labels: Tech Support
