### ISSUE TITLE
OoT3D/MM3D: drag-and-dropped assets now render entirely black

### ISSUE THREAD

**Issue by tom-overton** [magcius/noclip.website#568] opened 2023-01-25 19:33 UTC
For a long time, I've been investigating assets in OoT3D/MM3D by dragging-and-dropping them from the `romfs/actor` folder into noclip. This still works, but recently something broke involving how they're rendered or lit. Specifically, they render entirely black now:
![image](https://user-images.githubusercontent.com/12245827/214668229-c87713cf-ffc2-4624-9667-b4e2ac675cf1.png)

Looking at the recent list of commits, I suspect 387d0afbbd2c3765b45d342f298dba8af28f2a1b might be the cause of it, but I don't know enough how the code works to dig into any further detail.

Repro steps:
1. Navigate to noclip.website in your browser.
2. Drag-and-drop `romfs/actor/zelda_dekujr.zar` (or really *any* asset from this folder, they'll all exhibit the same problem) from an extracted copy of Ocarina of Time 3D onto your browser window.

**Comment by magcius** [comment] 2023-01-31 19:45
@M-1-RLG I suspect this was caused by your changes. Can you investigate?

**Comment by magcius** [comment] 2023-02-01 15:45
Should be fixed by abd5ea22484bae93a0c968fda07d2a98135e8e6f

**Closed by magcius** 2023-02-01 15:45 UTC
Labels: Broken Game

**Comment by tom-overton** [comment] 2023-02-02 01:21
Yep, it's fixed. Thanks so much for taking a look!
